language: go

go:
  - '1.8'
  - '1.9'
  - '1.10'

script:
  - curl -s https://raw.githubusercontent.com/go-task/task/master/install-task.sh | sh
  - bin/task dl-deps
  - bin/task lint
  - bin/task test
